# Generated by Django 4.2.4 on 2023-08-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currency',
            new_name='CryptoCurrency',
        ),
    ]
