# Generated by Django 4.2.4 on 2023-08-29 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0002_rename_currency_cryptocurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='cryptoapp.wallet'),
        ),
    ]
