# Generated by Django 4.2.4 on 2023-08-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0003_alter_portfolio_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
