# Generated by Django 4.2.4 on 2023-08-30 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0004_wallet_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('502f99e8-faef-45e4-b2d5-f24c6245a306')),
        ),
    ]
