# Generated by Django 4.2.4 on 2023-08-30 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0005_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('35f6d668-f27c-4e23-b152-b622d083eb40')),
        ),
    ]
