# Generated by Django 4.2.4 on 2023-08-31 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0006_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='coin_total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('1e4775cf-5a7c-4132-8e98-5b998d972236')),
        ),
    ]
