# Generated by Django 4.2.4 on 2023-08-31 16:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0007_portfolio_coin_total_value_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('7dfb4f05-4140-4b29-8ef8-fea67d07b25b')),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptoapp.cryptocurrency')),
                ('send_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coinssend', to='cryptoapp.wallet')),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coinsreceived', to='cryptoapp.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
