# Generated by Django 4.2.4 on 2023-08-31 17:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0009_transaction_status_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptoapp.cryptocurrency'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('73695e20-fb16-42f4-81f2-ef2d53d90575')),
        ),
    ]
