# Generated by Django 4.2.4 on 2023-08-31 18:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0010_alter_portfolio_currency_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='cryptoapp.cryptocurrency'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('30a45ea5-7951-4ae1-98f4-40d4a8b1c4d9')),
        ),
    ]
