# Generated by Django 4.2.4 on 2023-09-02 07:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0012_wallet_referral_code_alter_wallet_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='invited_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.UUID('e24ab5f6-0586-450a-a14c-a5c38674b514')),
        ),
    ]
